# Generated by Django 2.2.8 on 2020-10-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_20200102_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.RemoveField(
            model_name='post',
            name='viewed_users',
        ),
    ]
